package zaym.`in`.card5min.utils

var strPrivacy = "<h1>Политика конфиденциальности (Privacy Policy)</h1>\n" +
        "Мобильное приложение (mobile application) “{NAME}” - <a href=\"https://play.google.com/store/apps/details?id={PACKAGE}\">https://play.google.com/store/apps/details?id={PACKAGE}</a>\n" +
        "\u2028<br><br>\n" +
        "Эта страница информирует вас о нашей политике в отношении сбора, использования и раскрытия персональных данных при использовании нашего Сервиса и о вариантах, которые вы связали с этими данными.\n" +
        "This page informs you of our policies regarding the collection, use and disclosure of personal data when you use our Service and the choices you have associated with that data.\n" +
        "Мы используем ваши данные для предоставления и улучшения Сервиса. Используя Сервис, вы соглашаетесь на сбор и использование информации в соответствии с этой политикой. Если иное не определено в настоящей Политике конфиденциальности, термины, используемые в настоящей Политике конфиденциальности, имеют те же значения, что и в наших Условиях и положениях.\n" +
        "We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.\n" +
        "<br><br>\n" +
        "Определения - Definitions<br>\n" +
        "Сервис - Service<br>\n" +
        "Сервис - мобильное приложение “{NAME}”<br>\n" +
        "Service is the “{NAME}” mobile application.<br>\n" +
        "Персональные данные - Personal Data<br>\n" +
        "Персональные данные - это данные о живом человеке, которые могут быть идентифицированы по этим данным (или по той и другой информации, которая находится в нашем распоряжении или может оказаться в нашем распоряжении).<br>\n" +
        "Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).<br>\n" +
        "Данные пользования – Usage Data<br>\n" +
        "Данные пользования - это данные, которые автоматически собираются либо в результате использования Сервиса, либо из самой инфраструктуры Сервиса (например, продолжительность посещения страницы).<br>\n" +
        "Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).<br>\n" +
        "Куки-файлы - Cookies<br>\n" +
        "Куки-файлы – это небольшие файлы, хранящиеся навашем устройстве (компьютере или мобильном устройстве).<br>\n" +
        "Cookies are small files stored on your device (computer or mobile device).<br>\n" +
        "<br><br>\n" +
        "Сбор и использование информации - Information Collection and Use<br>\n" +
        "Мы собираем несколько различных типов информации для различных целей, чтобы предоставить вам и улучшить наш Сервис.<br>\n" +
        "We collect several different types of information for various purposes to provide and improve our Service to you.<br>\n" +
        "<br>\n" +
        "Типы собираемых данных - Types of Data Collected<br>\n" +
        "Персональные данные – Personal Data<br>\n" +
        "Во время использования нашего Сервиса мы можем попросить вас предоставить нам определенную личную информацию, которая может быть использована для установления вашей личности («Личные данные»). Личная информация может включать, но не ограничивается:<br>\n" +
        "• Адрес электронной почты<br>\n" +
        "• Имя и фамилия<br>\n" +
        "• Номер телефона<br>\n" +
        "• Адрес, штат, провинция, почтовый индекс, город<br>\n" +
        "• Cookies и данные об использовании<br>\n" +
        "While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (\"Personal Data\"). Personally identifiable information may include, but is not limited to:<br>\n" +
        "· Email address<br>\n" +
        "· First name and last name<br>\n" +
        "· Phone number<br>\n" +
        "· Address, State, Province, ZIP/Postal code, City<br>\n" +
        "· Cookies and Usage Data<br>\n" +
        "<br>\n" +
        "Данные пользования - Usage Data<br>\n" +
        "Когда вы получаете доступ к Сервису с помощью мобильного устройства, мы можем собирать определенную информацию автоматически, включая, помимо прочего, тип используемого вами мобильного устройства, уникальный идентификатор вашего мобильного устройства, IP-адрес вашего мобильного устройства, вашу мобильную операционную систему. тип используемого вами мобильного интернет-браузера, уникальные идентификаторы устройства и другие диагностические данные («Данные об использовании»).<br>\n" +
        "When you access the Service with a mobile device, we may collect certain information automatically, including, but not limited to, the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data (\"Usage Data\").<br>\n" +
        "Tracking Cookies Data<br>\n" +
        "Мы используем файлы cookie и аналогичные технологии отслеживания для отслеживания активности в нашем Сервисе, и мы храним определенную информацию.<br>\n" +
        "We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.<br>\n" +
        "Файлы cookie - это файлы с небольшим объемом данных, которые могут содержать анонимный уникальный идентификатор. Файлы cookie отправляются в ваш браузер с веб-сайта и сохраняются на вашем устройстве. Другие технологии отслеживания также используются, такие как маяки, теги и сценарии, для сбора и отслеживания информации, а также для улучшения и анализа нашего Сервиса.<br>\n" +
        "Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyse our Service.<br>\n" +
        "Вы можете указать браузеру отказаться от всех файлов cookie или указать, когда они отправляются. Однако, если вы не принимаете куки, вы не сможете использовать некоторые части нашего Сервиса.<br>\n" +
        "You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.<br>\n" +
        "<br>\n" +
        "Примеры файлов cookie, которые мы используем:<br>\n" +
        "• Сессионные куки. Мы используем SessionCookies для работы нашего Сервиса.<br>\n" +
        "• Предпочтительные файлы cookie. Мы используем файлы cookie предпочтений, чтобы запомнить ваши предпочтения и различные настройки.<br>\n" +
        "• Файлы cookie безопасности. Мы используем файлы cookie безопасности в целях безопасности.<br>\n" +
        "ExamplesofCookiesweuse:<br>\n" +
        "· Session Cookies. We use Session Cookies to operate our Service.<br>\n" +
        "· Preference Cookies. We use Preference Cookies to remember your preferences and various settings.<br>\n" +
        "· Security Cookies. We use Security Cookies for security purposes.<br>\n" +
        "<br>\n" +
        "Использование данных – Use of Data<br>\n" +
        "«{NAME}» использует собранные данные для различных целей:<br>\n" +
        "• Предоставлять и поддерживать наш Сервис<br>\n" +
        "• Чтобы уведомить вас об изменениях в нашем Сервисе<br>\n" +
        "• Чтобы позволить вам участвовать в интерактивных функциях нашего Сервиса, когда вы решите это сделать<br>\n" +
        "• Обеспечить поддержку клиентов<br>\n" +
        "• Собрать анализ или ценную информацию, чтобы мы могли улучшить наш Сервис<br>\n" +
        "• Контролировать использование нашего Сервиса<br>\n" +
        "• обнаруживать, предотвращать и решать технические проблемы<br>\n" +
        "«Займы онлайн» uses the collected data for various purposes:<br>\n" +
        "· To provide and maintain our Service<br>\n" +
        "· To notify you about changes to our Service<br>\n" +
        "· To allow you to participate in interactive features of our Service when you choose to do so<br>\n" +
        "· To provide customer support<br>\n" +
        "· To gather analysis or valuable information so that we can improve our Service<br>\n" +
        "· To monitor the usage of our Service<br>\n" +
        "· To detect, prevent and address technical issues<br>\n" +
        "<br>\n" +
        "Передачаданных - Transfer of Data<br>\n" +
        "Ваша информация, включая Личные данные, может передаваться и храниться на компьютерах, расположенных за пределами вашего региона, провинции, страны или другой государственной юрисдикции, где законы о защите данных могут отличаться от законов вашей юрисдикции. Персональные данные не хранятся в приложении и обрабатываются только на стороне финансовых организаций представленных в приложении.<br>\n" +
        "Your information, including Personal Data, may be transferred to - and maintained on - computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.Personal data is not collected in application and used only on the side of financial organizations presented in application.<br>\n" +
        "Ваше согласие с настоящей Политикой конфиденциальности, сопровождаемое предоставлением вами такой информации, означает ваше согласие на такую передачу.<br>\n" +
        "Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.<br>\n" +
        "«Займы онлайн» предпримет все разумно необходимые шаги для обеспечения безопасного обращения с вашими данными в соответствии с настоящей Политикой конфиденциальности, и передача ваших Личных данных в организацию или страну не будет осуществляться, если не будут приняты надлежащие меры контроля, включая безопасность ваших данных и другой личной информации.<br>\n" +
        "«Займы онлайн» will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.<br>\n" +
        "<br>\n" +
        "Раскрытие данных - Disclosure of Data<br>\n" +
        "<br>\n" +
        "Правовые требования - Legal Requirements<br>\n" +
        "«{NAME}» может раскрывать ваши Личные данные, добросовестно полагая, что такие действия необходимы для:<br>\n" +
        "• соблюдать юридическое обязательство<br>\n" +
        "• Для защиты и защиты прав или собственности «Займы онлайн»<br>\n" +
        "• Для предотвращения или расследования возможных нарушений в связи с использованием Сервиса.<br>\n" +
        "• Для защиты личной безопасности пользователей Сервиса или общественности.<br>\n" +
        "• Защитить от юридической ответственности<br>\n" +
        "«{NAME}» may disclose your Personal Data in the good faith belief that such action is necessary to:<br>\n" +
        "· To comply with a legal obligation<br>\n" +
        "· To protect and defend the rights or property of «{NAME}»<br>\n" +
        "· To prevent or investigate possible wrongdoing in connection with the Service<br>\n" +
        "· To protect the personal safety of users of the Service or the public<br>\n" +
        "· To protect against legal liability<br>\n" +
        "\n" +
        "Безопасность данных - Security of Data<br>\n" +
        "Безопасность ваших данных важна для нас, но помните, что ни один метод передачи через Интернет или метод электронного хранения не является на 100% безопасным. Хотя мы стремимся использовать коммерчески приемлемые средства для защиты ваших личных данных, мы не можем гарантировать их абсолютную безопасность.<br>\n" +
        "The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.<br>\n" +
        "<br>\n" +
        "Поставщики услуг – Service Providers<br>\n" +
        "Мы можем нанимать сторонние компании и частных лиц для оказания помощи нашему Сервису («Поставщики услуг»), предоставления Сервисов от нашего имени, оказания связанных с Сервисом услуг или оказания нам помощи в анализе того, как используется наш Сервис.Эти третьи стороны имеют доступ к вашим Личным данным только для выполнения этих задач от нашего имени и обязаны не разглашать или использовать их для каких-либо других целей.<br>\n" +
        "We may employ third party companies and individuals to facilitate our Service (\"Service Providers\"), provide the Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.<br>\n" +
        "<br>\n" +
        "Аналитика - Analytics<br>\n" +
        "Мы можем использовать сторонних поставщиков услуг для мониторинга и анализа использования наших услуг.<br>\n" +
        "We may use third-party Service Providers to monitor and analyse the use of our Service.<br>\n" +
        "<br>\n" +
        "Firebase<br>\n" +
        "Firebase - это аналитическая служба, предоставляемая GoogleInc.<br>\n" +
        "Вы можете отказаться от определенных функций Firebase через настройки вашего мобильного устройства, такие как настройки рекламы на вашем устройстве или следуя инструкциям, предоставленным Google в их Политике конфиденциальности: <a href=\"https://policies.google.com/privacy?hl=en\">https://policies.google.com/privacy?hl=en.</a><br>\n" +
        "Мы также рекомендуем вам ознакомиться с политикой Google в отношении защиты ваших данных: <a href=\"https://support.google.com/analytics/answer/6004245\">https://support.google.com/analytics/answer/6004245</a>.<br>\n" +
        "Для получения дополнительной информации о том, какой тип информации собирает Firebase, посетите веб-страницу Условия конфиденциальности Google: <a href=\"https://policies.google.com/privacy?hl=ru\">https://policies.google.com/privacy?hl=ru</a>.<br>\n" +
        "Firebase is analytics service provided by Google Inc.<br>\n" +
        "You may opt-out of certain Firebase features through your mobile device settings, such as your device advertising settings or by following the instructions provided by Google in their Privacy Policy: <a href=\"https://policies.google.com/privacy?hl=en\">https://policies.google.com/privacy?hl=en</a><br>\n" +
        "We also encourage you to review the Google's policy for safeguarding your data: <a href=\"https://support.google.com/analytics/answer/6004245\">https://support.google.com/analytics/answer/6004245</a>.<br>\n" +
        "For more information on what type of information Firebase collects, please visit the Google Privacy Terms web page: <a href=\"https://policies.google.com/privacy?hl=en\">https://policies.google.com/privacy?hl=en</a><br>\n" +
        "<br>\n" +
        "Ссылки на другие сайты - Links to Other Sites<br>\n" +
        "Наш Сервис может содержать ссылки на другие сайты, которые не управляются нами. Если вы нажмете на ссылку третьей стороны, вы будете перенаправлены на сайт этой третьей стороны. Мы настоятельно рекомендуем вам ознакомиться с Политикой конфиденциальности каждого посещаемого вами сайта.Мы не контролируем и не несем ответственности за содержание, политику конфиденциальности или действия любых сторонних сайтов или служб.<br>\n" +
        "Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.<br>\n" +
        "<br>\n" +
        "Конфиденциальность детей - Children's Privacy<br>\n" +
        "Наша Служба не предназначена для лиц младше 18 лет («Дети»). Мы сознательно не собираем личную информацию от лиц, не достигших 18 лет. Если вы являетесь родителем или опекуном и знаете, что ваш ребенок предоставил нам личные данные, пожалуйста, свяжитесь с нами. Если нам станет известно, что мы собрали Личные данные детей без подтверждения согласия родителей, мы предпринимаем шаги по удалению этой информации с наших серверов.<br>\n" +
        "Our Service does not address anyone under the age of 18 (\"Children\").We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.<br>\n" +
        "<br>\n" +
        "Изменения настоящей политики конфиденциальности - Changes to This Privacy Policy<br>\n" +
        "Мы можем обновлять нашу Политику конфиденциальности время от времени. Мы сообщим вам о любых изменениях, разместив новую Политику конфиденциальности на этой странице.До того, как изменения вступят в силу, мы сообщим вам об этом по электронной почте и / или в заметном уведомлении о нашем Сервисе и обновим «дату вступления в силу» в верхней части настоящей Политики конфиденциальности.Рекомендуется периодически просматривать настоящую Политику конфиденциальности на предмет любых изменений.<br> Изменения в настоящей Политике конфиденциальности вступают в силу с момента их публикации на этой странице.<br>\n" +
        "We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the \"effective date\" at the top of this Privacy Policy.You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.<br>\n" +
        "<br>\n" +
        "\uD83D\uDD0DУсловия получения:<br><br>\n" +
        "Для получения кредита, необходимо соблюсти следующие условия:<br>\n" +
        "- Минимальный срок погашения кредита составляет 62 дня;<br>\n" +
        "- Максимальный срок погашения кредита составляет 365 дней;<br>\n" +
        "<br>- Максимальная годовая процентная ставка, включающая ссудный процент, а также все остальные комиссии и расходы за год (Annual Percentage Rate APR) составляет 32%, а минимальная 1%. Годовой процент за пользование Кредитом - min 1%, max 32%.\n" +
        "<br>- Минимальная ставка за пользование кредитом в день составляет 0.01%;\n" +
        "<br>- Максимальная ставка за пользование кредитом в день составляет 1%;\n" +
        "<br>- Штраф за просрочку: 0,1% от суммы просрочки в день, но не более 10% от суммы кредита\n" +
        "<br>- Другие комиссии или сборы: отсутствуют\n" +
        "\n" +
        "<br><br>Пример расчета процентной ставки:\n" +
        "<br>- Сумма тела кредита – 20000 рублей.\n" +
        "<br>- Срок займа – 100 дней.\n" +
        "<br>- Комиссия за использование кредита: 0,08% в день, то есть 16 рублей в день, или 2,4% в месяц (усредненно для 30 дней), т.е. 480 рублей в месяц (усредненно для 30 дней).\n" +
        "<br>- Общая сумма комиссии за 100 дней составит 1600 рублей.\n" +
        "<br>- Общая сумма к возврату с учетом суммы займа: 21600 рублей.\n" +
        "<br>- ПСК - полная стоимость кредита (FLC - Full Loan Cost) в процентах составляет 29,2% годовых.\n" +
        "\n" +
        "<br><br>Последствия просрочки возврата кредита:\n" +
        "<br>В случае нарушения сроков выплаты онлайн займа, размер неустойки может составить 0,1% от общей суммы просрочки в день, но не более 10% от суммы всего кредита.\n" +
        "<br>\n" +
        "<br>\n" +
        "<br>\n" +
        "Требования к заемщикам:\n" +
        "<br>- возраст от 18 до 65 лет;\n" +
        "<br>- паспорт гражданина РФ.\n" +
        "<br>\n" +
        "<br>Перечень кредитных организаций:\n" +
        "<br>ООО «ХОУМ КРЕДИТ ЭНД ФИНАНС БАНК». Лицензия ЦБ РФ №316. г. Москва, ул. Правды 8\n" +
        "ООО МФК «Займер» ОГРН: 1134205019189 / Свидетельство №651303532004088 К\n" +
        "<br>ООО МФК «Мани Мен» — Свидетельство №2110177000478 от 25.10.2011 года.\n" +
        "<br>ООО МКК \"Русинтерфинанс\" (Екапуста) - Свидетельство №2120754001243 от 22.03.2012 года."+
        "<br><br>Contact Us<br>\n" +
        "Если у вас есть какие-либо вопросы об этой Политике конфиденциальности, пожалуйста, свяжитесь с нами.<br>\n" +
        "If you have any questions about this Privacy Policy, please contact us<br>\n" +
        "· По эл.почте указанной на аккаунте приложения «{NAME}» <a href=\"https://play.google.com/store/apps/details?id={PACKAGE}\">https://play.google.com/store/apps/details?id={PACKAGE}</a><br>\n"